version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfiles/.prod.Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules